// Base de données des annonces
// Pour ajouter une annonce : copie un bloc et remplis les champs
// loyer : en euros CC, coords : [lat, lng] depuis Google Maps (clic droit → coordonnées)

const ANNONCES = [
  {
    id: 1,
    titre: "Thiers · Musicien, Nice (06000)",
    sous_titre: "Appartement · Location vide",
    coords: [43.699889, 7.259306],
    zoom: 16,
    tooltip: "Thiers · Musicien · Nice",
    loyer: 1850,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/3pieces/hektor-gila3019-194",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "88 m²" },
      { label: "Pièces",             value: "3 pièces · 2 ch." },
      { label: "Étage",              value: "4e · avec ascenseur" },
      { label: "Meublé",             value: "❌ Non" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "2 balcons" },
      { label: "Année construction", value: "1975" },
      { label: "État",               value: "Entretenu" },
      { label: "DPE",                value: "D · GES D" },
      { label: "Chauffage",          value: "Gaz individuel" },
      { label: "Exposition",         value: "Est, Ouest" },
      { label: "Transports",         value: "🚋 Tram T2" },
    ],
    particularites: "🏛️ Immeuble bourgeois · 🛗 Ascenseur · 🔇 Calme · 🌊 Vue mer partielle",
    note: "Dernier étage avec ascenseur dans un immeuble bourgeois. Grande entrée, salon-salle à manger, cuisine indépendante équipée, 2 chambres, 2 balcons. Quartier des Musiciens, proche Jean Médecin et gare SNCF.",
  },
  /* ANNONCE EXPIRÉE #2 — Californie, Nice — annonce ne correspond plus
  {
    id: 2,
    titre: "Californie, Nice (06200)",
    sous_titre: "Appartement · Location meublée",
    coords: [43.686000, 7.237083],
    zoom: 16,
    tooltip: "Californie · Nice",
    loyer: 1050,
    lien: "https://www.seloger.com/annonces/locations/appartement/nice-06000/californie/26XT877Z52DQ.htm",
    source: "SeLoger",
    badges: [
      { label: "Surface",            value: "26 m²" },
      { label: "Pièces",             value: "2 pièces · 1 ch." },
      { label: "Étage",              value: "2e / 3 · sans ascenseur" },
      { label: "Meublé",             value: "✅ Oui" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "❌ Aucun" },
      { label: "Année construction", value: "Années 1960–70" },
      { label: "État",               value: "Entretenu" },
      { label: "DPE",                value: "D · GES B" },
      { label: "Chauffage",          value: "Clim réversible" },
      { label: "Exposition",         value: "Sud, Est" },
      { label: "Transports",         value: "🚋 Tram ligne 2" },
    ],
    particularites: "🌊 Vue mer depuis le séjour · 🔇 Chambre sur cour calme · 🎓 Proche EDHEC & IUT",
    note: "2ème étage sans ascenseur, vue mer depuis le séjour, chambre sur cour calme. Promenade des Anglais à deux pas.",
  },
  */

  /* ANNONCE EXPIRÉE #3 — Carré d'or, Nice (06000) — annonce retirée du marché
  {
    id: 3,
    titre: "Carré d'or, Nice (06000)",
    sous_titre: "Studio · Location meublée",
    coords: [43.697667, 7.266833],
    zoom: 16,
    tooltip: "Carré d'or · Nice",
    loyer: 760,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/1piece/globalgest-ETUDIANT_PARADIS_11",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "22 m²" },
      { label: "Pièces",             value: "1 pièce" },
      { label: "Étage",              value: "3e / 6 · sans ascenseur" },
      { label: "Meublé",             value: "✅ Oui" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "Entretenu" },
      { label: "DPE",                value: "C" },
      { label: "Chauffage",          value: "Électrique individuel" },
      { label: "Exposition",         value: "Est" },
      { label: "Transports",         value: "🚋 Tram · 🚌 Bus" },
    ],
    particularites: "🛣️ Rue piétonne calme · 🛍️ Commerces à pied · 🌊 Mer et plages proches · 🎓 Étudiant uniquement",
    note: "Studio au 3ème étage sans ascenseur, rue Paradis, rue piétonne calme. Coin cuisine équipé, salle d'eau avec WC. Double vitrage, climatisation réversible.",
  },
  */

  /* ANNONCE EXPIRÉE #4 — Carabacel, Nice (06000) — annonce retirée du marché
  {
    id: 4,
    titre: "Carabacel, Nice (06000)",
    sous_titre: "Appartement · Location meublée",
    coords: [43.700999, 7.274861],
    zoom: 16,
    tooltip: "Carabacel · Nice",
    loyer: 2000,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/3pieces/parnasse-86722094",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "76 m²" },
      { label: "Pièces",             value: "3 pièces · 1 ch. + mezzanine" },
      { label: "Étage",              value: "2e" },
      { label: "Meublé",             value: "✅ Oui" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "Balcon" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "Entretenu" },
      { label: "DPE",                value: "C · GES B" },
      { label: "Chauffage",          value: "Climatisation" },
      { label: "Exposition",         value: "Non communiquée" },
      { label: "Transports",         value: "🚋 Tram T2" },
    ],
    particularites: "🏰 Vue colline du château · 🌆 Cœur de Nice · 🛍️ Proche port et vieille ville · 🏠 Mezzanine",
    note: "2ème étage, séjour avec coin cuisine indépendant, une chambre, balcon vue château. Grande mezzanine avec chambre et salle d'eau à l'étage.",
  },
  */

  {
    id: 5,
    titre: "Saint-Sylvestre, Nice (06100)",
    sous_titre: "Appartement · Location vide",
    coords: [43.723444, 7.249944],
    zoom: 16,
    tooltip: "Saint-Sylvestre · Nice",
    loyer: 1380,
    lien: "https://www.seloger.com/annonce/location/provence-alpes-cote-d-azur/alpes-maritimes-06/nice-06000/26LWV57RVXY5",
    source: "SeLoger",
    badges: [
      { label: "Surface",            value: "68,71 m²" },
      { label: "Pièces",             value: "3 pièces · 2 ch." },
      { label: "Étage",              value: "3e / 6 · avec ascenseur" },
      { label: "Meublé",             value: "❌ Non" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "Terrasse 14 m²" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "Entièrement rénové" },
      { label: "DPE",                value: "Non communiqué" },
      { label: "Chauffage",          value: "Chauffage au sol" },
      { label: "Exposition",         value: "Traversant" },
      { label: "Transports",         value: "🚋 Tram à proximité" },
    ],
    particularites: "🔨 Entièrement rénové · 🌿 Terrasse · 🔇 Résidence calme · 🏠 Cave incluse · 🌆 Belle vue",
    note: "3ème étage avec ascenseur dans résidence calme, 11 rue Valentiny. Appartement traversant et lumineux, séjour avec terrasse, 2 chambres, nombreux rangements. Cave.",
  },

  {
    id: 6,
    titre: "Carabacel · Tonduti, Nice (06000)",
    sous_titre: "Appartement · Location meublée",
    coords: [43.701185, 7.275985],
    zoom: 16,
    tooltip: "Carabacel · Tonduti · Nice",
    loyer: 1900,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/3pieces/apimo-87331733",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "76 m²" },
      { label: "Pièces",             value: "3-4 pièces · 2 ch. + mezzanine" },
      { label: "Étage",              value: "4e" },
      { label: "Meublé",             value: "✅ Oui" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "Balcon filant" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "Entièrement rénové" },
      { label: "DPE",                value: "A · GES A" },
      { label: "Chauffage",          value: "Climatisation électrique individuelle" },
      { label: "Exposition",         value: "Traversant" },
      { label: "Transports",         value: "🚋 Tram à proximité" },
    ],
    particularites: "🔨 Entièrement rénové · 🌆 Plein centre · 🔇 Calme · 🏠 Mezzanine · ❄️ Climatisation",
    note: "Appartement traversant entièrement rénové avec goût. Grand séjour avec belle hauteur sous plafond, cuisine américaine équipée, 2 chambres, 2 salles d'eau, balcon filant. Proche tram et toutes commodités du centre.",
  },
  {
    id: 7,
    titre: "Vieux Nice, Nice (06300)",
    sous_titre: "Appartement · Location meublée",
    coords: [43.697051, 7.277171],
    zoom: 16,
    tooltip: "Vieux Nice, Nice (06300)",
    loyer: 967,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/2pieces/immo-facile-50597392?q=%2Frecherche%2Flocation%2Fnice-06000",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "24.1 m²" },
      { label: "Pièces", value: "2 pièces · 1 ch." },
      { label: "Étage", value: "1e" },
      { label: "Meublé", value: "✅ Oui" },
      { label: "Parking", value: "❌ Non" },
      { label: "Extérieur", value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État", value: "Entretenu" },
      { label: "DPE", value: "D · GES A" },
      { label: "Chauffage", value: "Non communiqué" },
      { label: "Exposition", value: "Non communiquée" },
      { label: "Transports", value: "Non communiqué" },
    ],
    particularites: "🔨 Rénové · 🛋️ Meublé",
    note: "Au coeur du Vieux-Nice, idéalement situé rue droite à quelques pas de la Place Rossetti, nous vous proposons à la location ce studio avec mezzanine totalement rénové avec prestations de très bon standing, meublé et entièrement équipé, disposant d'une salle d'eau et wc.",
  },
  /* DOUBLON #8 — même annonce que #7 (immo-facile-50597392)
  {
    id: 8,
    titre: "Vieux Nice, Nice (06300)",
    sous_titre: "Appartement · Location meublée",
    coords: [43.697051, 7.277171],
    zoom: 16,
    tooltip: "Vieux Nice, Nice (06300)",
    loyer: 967,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/2pieces/immo-facile-50597392?q=%2Frecherche%2Flocation%2Fnice-06000",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "24.1 m²" },
      { label: "Pièces", value: "2 pièces · 1 ch." },
      { label: "Étage", value: "1e" },
      { label: "Meublé", value: "✅ Oui" },
      { label: "Parking", value: "❌ Non" },
      { label: "Extérieur", value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État", value: "Entretenu" },
      { label: "DPE", value: "D · GES A" },
      { label: "Chauffage", value: "Non communiqué" },
      { label: "Exposition", value: "Non communiquée" },
      { label: "Transports", value: "Non communiqué" },
    ],
    particularites: "🔨 Rénové · 🛋️ Meublé",
    note: "Au coeur du Vieux-Nice, idéalement situé rue droite à quelques pas de la Place Rossetti, nous vous proposons à la location ce studio avec mezzanine totalement rénové avec prestations de très bon standing, meublé et entièrement équipé, disposant d'une salle d'eau et wc.",
  },
  */
  {
    id: 9,
    titre: "Vieux Nice, Nice (06300)",
    sous_titre: "Appartement · Location meublée",
    coords: [43.696616, 7.276849],
    zoom: 16,
    tooltip: "Vieux Nice, Nice (06300)",
    loyer: 1095,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/2pieces/gedeon-33799899?q=%2Frecherche%2Flocation%2Fnice-06000",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "38 m²" },
      { label: "Pièces", value: "2 pièces · 1 ch." },
      { label: "Étage", value: "5e" },
      { label: "Meublé", value: "✅ Oui" },
      { label: "Parking", value: "❌ Non" },
      { label: "Extérieur", value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État", value: "Entretenu" },
      { label: "DPE", value: "D · GES B" },
      { label: "Chauffage", value: "Non communiqué" },
      { label: "Exposition", value: "Non communiquée" },
      { label: "Transports", value: "Non communiqué" },
    ],
    particularites: "🔇 Calme · 🛋️ Meublé",
    note: "Idéalement situé au cœur du vieux NICE rue de la préfecture. Appartement deux pièces en dernier étage composé d'une entrée avec grand séjour, salle à manger, une cuisine ouverte au calme absolu. Coté nuit un grand espace sous les toits avec chambre rangements vélux.",
  },
  /* ANNONCE INCOMPLÈTE #10 — PAP données incorrectes (coords et note erronées)
  { id: 10, ... }
  */

  /* ANNONCE INCOMPLÈTE #11 — PAP données incorrectes (coords et note erronées)
  { id: 11, ... }
  */

  /* ANNONCE SANS LIEN #12 — Saint-Lambert, Nice — lien SeLoger non récupéré
  { id: 12, ... }
  */
  {
    id: 29,
    titre: "Saint-Sylvestre, 1p · 36.93m²",
    sous_titre: "Nice · 06100",
    coords: [43.71599, 7.25369],
    zoom: 16,
    tooltip: "Saint-Sylvestre",
    loyer: 850,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/1piece/century-21-202_3526_1092",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "36.93 m²" },
      { label: "Pièces", value: "1" },
      { label: "Meublé", value: "Non" },
      { label: "DPE", value: "D" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 30,
    titre: "Saint-Lambert - Bas-Cimiez, 3p · ?m²",
    sous_titre: "Nice · 06100",
    coords: [43.712, 7.26405],
    zoom: 16,
    tooltip: "Saint-Lambert - Bas-Cimiez",
    loyer: 1225,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/3pieces/apimo-7382746",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "?" },
      { label: "Pièces", value: "3" },
      { label: "Meublé", value: "Oui" },
      { label: "DPE", value: "C" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 31,
    titre: "Saint-Philippe - Estienne d'Orves, 2p · 50m²",
    sous_titre: "Nice · 06000",
    coords: [43.70978, 7.24724],
    zoom: 16,
    tooltip: "Saint-Philippe - Estienne d'Orves",
    loyer: 1200,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/2pieces/apimo-87286766",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "50 m²" },
      { label: "Pièces", value: "2" },
      { label: "Meublé", value: "Non" },
      { label: "DPE", value: "C" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 32,
    titre: "Saint-Sylvestre, 3p · 60.27m²",
    sous_titre: "Nice · 06100",
    coords: [43.71973, 7.25645],
    zoom: 16,
    tooltip: "Saint-Sylvestre",
    loyer: 1164,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/3pieces/citya-immobilier-1127-GES82770048-53",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "60.27 m²" },
      { label: "Pièces", value: "3" },
      { label: "Meublé", value: "Oui" },
      { label: "DPE", value: "D" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 33,
    titre: "Saint-Roch, 4p · 52.6m²",
    sous_titre: "Nice · 06300",
    coords: [43.70863, 7.29308],
    zoom: 16,
    tooltip: "Saint-Roch",
    loyer: 1600,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/4pieces/apimo-87364337",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "52.6 m²" },
      { label: "Pièces", value: "4" },
      { label: "Meublé", value: "Oui" },
      { label: "DPE", value: "C" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 34,
    titre: "Thiers - Musicien, 1p · 33.93m²",
    sous_titre: "Nice · 06000",
    coords: [43.70179, 7.25968],
    zoom: 16,
    tooltip: "Thiers - Musicien",
    loyer: 1090,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/1piece/apimo-87359367",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "33.93 m²" },
      { label: "Pièces", value: "1" },
      { label: "Meublé", value: "Oui" },
      { label: "DPE", value: "D" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 35,
    titre: "Californie - Carras, 2p · 26.05m²",
    sous_titre: "Nice · 06200",
    coords: [43.68609, 7.23701],
    zoom: 16,
    tooltip: "Californie - Carras",
    loyer: 1050,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/2pieces/apimo-87350359",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "26.05 m²" },
      { label: "Pièces", value: "2" },
      { label: "Meublé", value: "Oui" },
      { label: "DPE", value: "C" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 36,
    titre: "Riquier, 3p · 63m²",
    sous_titre: "Nice · 06300",
    coords: [43.70428, 7.28662],
    zoom: 16,
    tooltip: "Riquier",
    loyer: 1890,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/3pieces/century-21-202_579_16907",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "63 m²" },
      { label: "Pièces", value: "3" },
      { label: "Meublé", value: "Oui" },
      { label: "DPE", value: "B" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 37,
    titre: "Saint-Philippe - Estienne d'Orves, 3p · 45.57m²",
    sous_titre: "Nice · 06000",
    coords: [43.70737, 7.2515],
    zoom: 16,
    tooltip: "Saint-Philippe - Estienne d'Orves",
    loyer: 1310,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/3pieces/citya-immobilier-1127-GES84870328-53",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "45.57 m²" },
      { label: "Pièces", value: "3" },
      { label: "Meublé", value: "Oui" },
      { label: "DPE", value: "D" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 38,
    titre: "Saint-Maurice, 2p · 57m²",
    sous_titre: "Nice · 06100",
    coords: [43.72523, 7.25922],
    zoom: 16,
    tooltip: "Saint-Maurice",
    loyer: 1100,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/2pieces/ag064863-548280395",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "57 m²" },
      { label: "Pièces", value: "2" },
      { label: "Meublé", value: "Oui" },
      { label: "DPE", value: "D" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 39,
    titre: "Saint-Philippe - Estienne d'Orves, 1p · 17.75m²",
    sous_titre: "Nice · 06000",
    coords: [43.70302, 7.24477],
    zoom: 16,
    tooltip: "Saint-Philippe - Estienne d'Orves",
    loyer: 650,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/1piece/apimo-87315872",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "17.75 m²" },
      { label: "Pièces", value: "1" },
      { label: "Meublé", value: "Oui" },
      { label: "DPE", value: "C" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 40,
    titre: "Caucade, 2p · 36m²",
    sous_titre: "Nice · 06200",
    coords: [43.67821, 7.2238],
    zoom: 16,
    tooltip: "Caucade",
    loyer: 1170,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/2pieces/ag065699-547771631",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "36 m²" },
      { label: "Pièces", value: "2" },
      { label: "Meublé", value: "Oui" },
      { label: "DPE", value: "C" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 41,
    titre: "Vernier, 3p · 54m²",
    sous_titre: "Nice · 06000",
    coords: [43.70827, 7.26113],
    zoom: 16,
    tooltip: "Vernier",
    loyer: 1650,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/3pieces/ag060571-547729850",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "54 m²" },
      { label: "Pièces", value: "3" },
      { label: "Meublé", value: "Oui" },
      { label: "DPE", value: "B" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 42,
    titre: "Cessole, 2p · 46m²",
    sous_titre: "Nice · 06100",
    coords: [43.71146, 7.25549],
    zoom: 16,
    tooltip: "Cessole",
    loyer: 1120,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/2pieces/hektor-ICV06340-1128",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "46 m²" },
      { label: "Pièces", value: "2" },
      { label: "Meublé", value: "Non" },
      { label: "DPE", value: "C" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 43,
    titre: "Carré d'or, 2p · 44.86m²",
    sous_titre: "Nice · 06000",
    coords: [43.69572, 7.26067],
    zoom: 16,
    tooltip: "Carré d'or",
    loyer: 1712,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/2pieces/apimo-85418724",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "44.86 m²" },
      { label: "Pièces", value: "2" },
      { label: "Meublé", value: "Non" },
      { label: "DPE", value: "C" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 44,
    titre: "Carré d'or, 2p · 24.56m²",
    sous_titre: "Nice · 06000",
    coords: [43.69697, 7.26111],
    zoom: 16,
    tooltip: "Carré d'or",
    loyer: 904,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/2pieces/apimo-84003939",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "24.56 m²" },
      { label: "Pièces", value: "2" },
      { label: "Meublé", value: "Non" },
      { label: "DPE", value: "C" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 45,
    titre: "Carré d'or, 1p · 28.75m²",
    sous_titre: "Nice · 06000",
    coords: [43.69739, 7.26618],
    zoom: 16,
    tooltip: "Carré d'or",
    loyer: 820,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/1piece/hektor-gila3019-131",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "28.75 m²" },
      { label: "Pièces", value: "1" },
      { label: "Meublé", value: "Oui" },
      { label: "DPE", value: "C" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 46,
    titre: "Baumettes, 2p · 28.08m²",
    sous_titre: "Nice · 06000",
    coords: [43.69368, 7.24636],
    zoom: 16,
    tooltip: "Baumettes",
    loyer: 1200,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/2pieces/netty-company51012fvn-appt-24509",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "28.08 m²" },
      { label: "Pièces", value: "2" },
      { label: "Meublé", value: "Oui" },
      { label: "DPE", value: "C" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 47,
    titre: "Thiers - Musicien, 3p · 77.06m²",
    sous_titre: "Nice · 06000",
    coords: [43.70004, 7.25795],
    zoom: 16,
    tooltip: "Thiers - Musicien",
    loyer: 1800,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/3pieces/ifsp6a-5433482",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "77.06 m²" },
      { label: "Pièces", value: "3" },
      { label: "Meublé", value: "Oui" },
      { label: "DPE", value: "C" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 48,
    titre: "Mont-Boron, 2p · 63.08m²",
    sous_titre: "Nice · 06300",
    coords: [43.68951, 7.29646],
    zoom: 16,
    tooltip: "Mont-Boron",
    loyer: 1790,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/2pieces/century-21-202_579_16936",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "63.08 m²" },
      { label: "Pièces", value: "2" },
      { label: "Meublé", value: "Non" },
      { label: "DPE", value: "C" },
    ],
    particularites: "",
    note: "",
  },
  {
    id: 49,
    titre: "Caucade, 3p · 71.34m²",
    sous_titre: "Nice · 06200",
    coords: [43.67516, 7.21159],
    zoom: 16,
    tooltip: "Caucade",
    loyer: 1940,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/3pieces/iad-france-1012633",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "71.34 m²" },
      { label: "Pièces", value: "3" },
      { label: "Meublé", value: "Oui" },
      { label: "DPE", value: "D" },
      { label: "Terrasse", value: "✓" },
    ],
    particularites: "",
    note: "",
  },




























  // --- Ajoute tes prochaines annonces ici ---

  {
    id: 13,
    titre: "Vieux Nice, Nice (06000)",
    sous_titre: "Appartement · Location vide",
    coords: [43.696326, 7.276146],
    zoom: 16,
    tooltip: "Vieux Nice · Nice",
    loyer: 1617,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/4pieces/ag060571-536275757",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "116 m²" },
      { label: "Pièces",             value: "4 pièces · 3 ch." },
      { label: "Étage",              value: "2e" },
      { label: "Meublé",             value: "❌ Non" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "Entretenu" },
      { label: "DPE",                value: "E · GES B" },
      { label: "Chauffage",          value: "Individuel" },
      { label: "Exposition",         value: "Non communiquée" },
      { label: "Transports",         value: "🚋 Tram à proximité" },
    ],
    particularites: "🏛️ Immeuble de caractère · 🌆 Vieux-Nice · 🏠 Atypique",
    note: "Appartement atypique de 4 pièces, 117 m², au cœur du Vieux-Nice secteur Benoît-Bunico/Préfecture. 2e étage d'un immeuble niçois de caractère.",
  },

  {
    id: 14,
    titre: "Vieux Nice, Nice (06300)",
    sous_titre: "Studio · Location meublée",
    coords: [43.694559, 7.276147],
    zoom: 16,
    tooltip: "Vieux Nice · Nice",
    loyer: 880,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/1piece/apimo-7354732",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "22,9 m²" },
      { label: "Pièces",             value: "1 pièce" },
      { label: "Étage",              value: "1e" },
      { label: "Meublé",             value: "✅ Oui" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "Entretenu" },
      { label: "DPE",                value: "F · GES D" },
      { label: "Chauffage",          value: "Radiateur électrique" },
      { label: "Exposition",         value: "Non communiquée" },
      { label: "Transports",         value: "🚋 Tram à proximité" },
    ],
    particularites: "🔇 Calme · 🌆 Vieux-Nice · ❄️ Climatisation · 🎓 Location étudiante (sept–mai)",
    note: "Studio meublé au calme au cœur du Vieux-Nice. Pièce principale, cuisine, salle d'eau avec WC. Location étudiante du 15 septembre au 31 mai. Proche tramway.",
  },

  {
    id: 15,
    titre: "Vieux Nice, Nice (06300)",
    sous_titre: "Loft · Location meublée",
    coords: [43.695529, 7.275597],
    zoom: 16,
    tooltip: "Vieux Nice · Nice",
    loyer: 2100,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/1piece/apimo-87303683",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "50,9 m²" },
      { label: "Pièces",             value: "1 pièce · 1 ch." },
      { label: "Étage",              value: "2e · sans ascenseur" },
      { label: "Meublé",             value: "✅ Oui" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "Entretenu" },
      { label: "DPE",                value: "B · GES A" },
      { label: "Chauffage",          value: "Climatisation électrique" },
      { label: "Exposition",         value: "Non communiquée" },
      { label: "Transports",         value: "🚋 Tram · 🏖️ Promenade à deux pas" },
    ],
    particularites: "🏠 Loft · ☀️ Lumineux · ❄️ Climatisation · 🌆 Vieux-Nice",
    note: "Superbe loft meublé au 2e étage, à deux pas de la Promenade des Anglais. Grande cuisine équipée, double séjour lumineux, chambre en mezzanine.",
  },

  {
    id: 16,
    titre: "Carabacel, Nice (06000)",
    sous_titre: "Appartement · Location meublée",
    coords: [43.705175, 7.268926],
    zoom: 16,
    tooltip: "Carabacel · Nice",
    loyer: 1990,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/3pieces/apimo-87359021",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "76 m²" },
      { label: "Pièces",             value: "3 pièces · 2 ch." },
      { label: "Étage",              value: "4e" },
      { label: "Meublé",             value: "✅ Oui" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "Entretenu" },
      { label: "DPE",                value: "D · GES D" },
      { label: "Chauffage",          value: "Radiateur gaz individuel" },
      { label: "Exposition",         value: "Non communiquée" },
      { label: "Transports",         value: "🚋 Tram à proximité" },
    ],
    particularites: "🏛️ Belle Époque · 🌆 Plein centre · ❄️ Climatisation · 🏠 Caractère",
    note: "Appartement 3 pièces de caractère au 11 rue de Paris, dans la Maison Sassi, immeuble emblématique Belle Époque. Entièrement meublé, situé en plein centre de Nice.",
  },

  {
    id: 17,
    titre: "Carabacel, Nice (06000)",
    sous_titre: "Appartement · Location meublée",
    coords: [43.704958, 7.270404],
    zoom: 16,
    tooltip: "Carabacel · Nice",
    loyer: 1750,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/2pieces/citya-immobilier-1192-GES31390178-96",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "55 m²" },
      { label: "Pièces",             value: "2 pièces · 1 ch." },
      { label: "Étage",              value: "6e" },
      { label: "Meublé",             value: "✅ Oui" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "Rénové" },
      { label: "DPE",                value: "D · GES D" },
      { label: "Chauffage",          value: "Radiateur gaz collectif" },
      { label: "Exposition",         value: "Non communiquée" },
      { label: "Transports",         value: "🚋 Tram à proximité" },
    ],
    particularites: "🌆 Centre-ville · 🔨 Rénové · ❄️ Climatisation",
    note: "T2 rénové au 6e étage, cœur de Nice quartier Centre Ville. 55 m², cadre moderne, idéal pour un professionnel ou un couple.",
  },

  {
    id: 18,
    titre: "Carabacel, Nice (06000)",
    sous_titre: "Studio · Location meublée",
    coords: [43.701811, 7.277287],
    zoom: 16,
    tooltip: "Carabacel · Nice",
    loyer: 900,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/1piece/apimo-87353782",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "26,9 m²" },
      { label: "Pièces",             value: "1 pièce" },
      { label: "Étage",              value: "5e" },
      { label: "Meublé",             value: "✅ Oui" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "Entièrement rénové" },
      { label: "DPE",                value: "C · GES A" },
      { label: "Chauffage",          value: "Climatisation électrique" },
      { label: "Exposition",         value: "Non communiquée" },
      { label: "Transports",         value: "🚋 Tram · proche MAMAC" },
    ],
    particularites: "🔨 Rénové à neuf · ❄️ Clim · 🌐 Wifi inclus · 💡 Charges incluses · 🎓 Bail mobilité",
    note: "Studio entièrement refait à neuf au 5e étage, bail étudiant ou mobilité. Eau chaude/froide, électricité, wifi inclus. À deux pas du MAMAC.",
  },

  {
    id: 19,
    titre: "Gambetta, Nice (06000)",
    sous_titre: "Appartement · Location meublée",
    coords: [43.701143, 7.255107],
    zoom: 16,
    tooltip: "Gambetta · Nice",
    loyer: 1290,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/3pieces/apimo-87306336",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "55 m²" },
      { label: "Pièces",             value: "3 pièces · 2 ch." },
      { label: "Étage",              value: "3e · avec ascenseur" },
      { label: "Meublé",             value: "✅ Oui" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "Entièrement rénové" },
      { label: "DPE",                value: "C · GES C" },
      { label: "Chauffage",          value: "Climatisation électrique" },
      { label: "Exposition",         value: "Non communiquée" },
      { label: "Transports",         value: "🚋 Tram à proximité" },
    ],
    particularites: "🔨 Entièrement rénové · ❄️ Climatisation · 🎓 Location étudiante",
    note: "Appartement 3 pièces de 55 m² entièrement rénové et meublé, 5e étage avec ascenseur. Deux chambres, location étudiante. Quartier Gambetta.",
  },

  {
    id: 20,
    titre: "Parc Impérial · Le Piol, Nice (06000)",
    sous_titre: "Appartement · Location meublée",
    coords: [43.702889, 7.255448],
    zoom: 16,
    tooltip: "Parc Impérial · Nice",
    loyer: 1192,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/2pieces/apimo-87306630",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "37 m²" },
      { label: "Pièces",             value: "2 pièces · 1 ch." },
      { label: "Étage",              value: "RDC" },
      { label: "Meublé",             value: "✅ Oui" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "Entretenu" },
      { label: "DPE",                value: "F · GES F" },
      { label: "Chauffage",          value: "Climatisation individuelle" },
      { label: "Exposition",         value: "Non communiquée" },
      { label: "Transports",         value: "🚋 Proche gare Nice-Ville" },
    ],
    particularites: "🏛️ Charme de l'ancien · ❄️ Climatisation · 🚉 Proche gare",
    note: "Agréable 2 pièces meublé au charme de l'ancien, 2 boulevard Tzaréwitch. Proche commerces, transports et gare de Nice-Ville.",
  },

  {
    id: 21,
    titre: "Riquier · Port, Nice (06300)",
    sous_titre: "Appartement · Location meublée",
    coords: [43.701499, 7.285441],
    zoom: 16,
    tooltip: "Riquier · Port · Nice",
    loyer: 1600,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/3pieces/apimo-87354842",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "70 m²" },
      { label: "Pièces",             value: "3 pièces · 2 ch." },
      { label: "Étage",              value: "3e" },
      { label: "Meublé",             value: "✅ Oui" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "Terrasse" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "Entretenu" },
      { label: "DPE",                value: "B · GES A" },
      { label: "Chauffage",          value: "Climatisation électrique" },
      { label: "Exposition",         value: "Non communiquée" },
      { label: "Transports",         value: "🚋 Tram · 🚢 Proche port" },
    ],
    particularites: "🌿 Terrasse · ❄️ Climatisation · 🚢 Proche port",
    note: "Appartement 3 pièces meublé de 70 m² avec terrasse, 3e étage, place Cigalusa près du port de Nice. DPE B, climatisation, deux chambres.",
  },

  {
    id: 22,
    titre: "Riquier, Nice (06300)",
    sous_titre: "Appartement · Location vide",
    coords: [43.703352, 7.286781],
    zoom: 16,
    tooltip: "Riquier · Nice",
    loyer: 1500,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/3pieces/nestenn-1-99939646335",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "70 m²" },
      { label: "Pièces",             value: "3 pièces · 2 ch." },
      { label: "Étage",              value: "3e" },
      { label: "Meublé",             value: "❌ Non" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "Balcon" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "Entretenu" },
      { label: "DPE",                value: "Non communiqué · GES D" },
      { label: "Chauffage",          value: "Non communiqué" },
      { label: "Exposition",         value: "Non communiquée" },
      { label: "Transports",         value: "🚋 Tram Riquier" },
    ],
    particularites: "🌿 Balcon · ❄️ Climatisation · 🏘️ Quartier Riquier",
    note: "3 pièces vide de 70 m² au 3e étage, secteur Riquier. Deux balcons, climatisation. Quartier prisé proche port et vieux-Nice.",
  },

  {
    id: 23,
    titre: "Acropolis · République, Nice (06300)",
    sous_titre: "Appartement · Location meublée",
    coords: [43.705650, 7.285699],
    zoom: 16,
    tooltip: "Acropolis · République · Nice",
    loyer: 1380,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/2pieces/apimo-86218788",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "43 m²" },
      { label: "Pièces",             value: "2 pièces · 1 ch." },
      { label: "Étage",              value: "1e" },
      { label: "Meublé",             value: "✅ Oui" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "Terrasse 15 m²" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "Rénové" },
      { label: "DPE",                value: "C · GES A" },
      { label: "Chauffage",          value: "Climatisation électrique" },
      { label: "Exposition",         value: "Non communiquée" },
      { label: "Transports",         value: "🚋 Tram TNL · Gare Riquier" },
    ],
    particularites: "🌿 Terrasse 15 m² · ❄️ Climatisation · 🏡 Résidence avec gardien · 🌳 Jardin",
    note: "2 pièces rénové et meublé avec goût, vaste terrasse de 15 m², dans résidence sécurisée avec gardien et jardin arboré. Secteur Carrefour TNL / Gare Riquier.",
  },

  {
    id: 24,
    titre: "Acropolis · République, Nice (06300)",
    sous_titre: "Appartement · Location vide",
    coords: [43.706713, 7.284159],
    zoom: 16,
    tooltip: "Acropolis · République · Nice",
    loyer: 1329,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/3pieces/ag060571-544933874",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "56 m²" },
      { label: "Pièces",             value: "3 pièces · 2 ch." },
      { label: "Étage",              value: "3e · sans ascenseur" },
      { label: "Meublé",             value: "❌ Non" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "Balcon" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "Entièrement rénové" },
      { label: "DPE",                value: "D · GES D" },
      { label: "Chauffage",          value: "Gaz individuel" },
      { label: "Exposition",         value: "Traversant" },
      { label: "Transports",         value: "🚋 Tram République" },
    ],
    particularites: "🔨 Entièrement rénové · 🌿 Balcon · 🔄 Traversant",
    note: "3 pièces de 56 m² entièrement rénové et traversant, 3e étage sans ascenseur. Secteur République/Acropolis. Balcon, deux chambres.",
  },

  {
    id: 25,
    titre: "Valrose · Cimiez, Nice (06000)",
    sous_titre: "Appartement · Location non meublée",
    coords: [43.710273, 7.267792],
    zoom: 16,
    tooltip: "Valrose · Cimiez · Nice",
    loyer: 1950,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/3pieces/apimo-87334265",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "71 m²" },
      { label: "Pièces",             value: "3 pièces · 2 ch." },
      { label: "Étage",              value: "4e" },
      { label: "Meublé",             value: "❌ Non" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "En cours de rénovation" },
      { label: "DPE",                value: "D · GES D" },
      { label: "Chauffage",          value: "Radiateur collectif" },
      { label: "Exposition",         value: "Non communiquée" },
      { label: "Transports",         value: "🚋 Tram Valrose" },
    ],
    particularites: "🏘️ Quartier Cimiez · 🔨 Rénovation en cours",
    note: "3 pièces de 71 m² au 4e étage dans le quartier recherché de Cimiez. Deux chambres, travaux de rénovation en cours. Disponible octobre 2026.",
  },

  {
    id: 26,
    titre: "Borriglione, Nice (06100)",
    sous_titre: "Chambre en colocation · Location meublée",
    coords: [43.712133, 7.262399],
    zoom: 16,
    tooltip: "Borriglione · Nice",
    loyer: 600,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/1piece/twimmo-2205466",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "20 m²" },
      { label: "Pièces",             value: "1 pièce (colocation 3 ch.)" },
      { label: "Étage",              value: "1e" },
      { label: "Meublé",             value: "✅ Oui" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "Entretenu" },
      { label: "DPE",                value: "C · GES B" },
      { label: "Chauffage",          value: "Collectif (inclus)" },
      { label: "Exposition",         value: "Non communiquée" },
      { label: "Transports",         value: "🚋 Tram à proximité" },
    ],
    particularites: "🎓 Étudiant exclusivement · 💡 Charges incluses · 🤝 Colocation",
    note: "Chambre en colocation étudiante, 20 rue Michel-Ange. Bail annuel meublé, 3 chambres au total. Eau chaude/froide et chauffage inclus dans les charges.",
  },

  {
    id: 27,
    titre: "Saint-Lambert · Bas-Cimiez, Nice (06000)",
    sous_titre: "Studio · Location meublée",
    coords: [43.714704, 7.262574],
    zoom: 16,
    tooltip: "Saint-Lambert · Bas-Cimiez · Nice",
    loyer: 799,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/1piece/ag752861-507991589",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "21 m²" },
      { label: "Pièces",             value: "1 pièce" },
      { label: "Étage",              value: "4e" },
      { label: "Meublé",             value: "✅ Oui" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "Entretenu" },
      { label: "DPE",                value: "B · GES B" },
      { label: "Chauffage",          value: "Électrique (inclus)" },
      { label: "Exposition",         value: "Non communiquée" },
      { label: "Transports",         value: "🚋 Tram à proximité" },
    ],
    particularites: "🎓 Jeunes actifs · 💡 Eau froide incluse · ❄️ Chauffage électrique",
    note: "Studio meublé et équipé de 21 m², 4e étage, quartier Saint-Lambert/Bas-Cimiez. Eau froide incluse. Idéal étudiant ou jeune actif.",
  },

  {
    id: 28,
    titre: "Cimiez, Nice (06000)",
    sous_titre: "Studio · Location vide",
    coords: [43.714251, 7.274302],
    zoom: 16,
    tooltip: "Cimiez · Nice",
    loyer: 840,
    lien: "https://www.bienici.com/annonce/location/nice/appartement/1piece/netty-company56146lrb-appt-11324",
    source: "Bien'ici",
    badges: [
      { label: "Surface",            value: "26 m²" },
      { label: "Pièces",             value: "1 pièce" },
      { label: "Étage",              value: "4e" },
      { label: "Meublé",             value: "❌ Non" },
      { label: "Parking",            value: "❌ Non" },
      { label: "Extérieur",          value: "Terrasse" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État",               value: "Entretenu" },
      { label: "DPE",                value: "E · GES B" },
      { label: "Chauffage",          value: "Chauffage au sol" },
      { label: "Exposition",         value: "Non communiquée" },
      { label: "Transports",         value: "🚋 Tram à proximité" },
    ],
    particularites: "🌊 Vue mer · 🌿 Terrasse · 🏡 Copropriété Jardin Cennelum · 🌳 Verdure",
    note: "Grand studio de 26 m² avec terrasse et vue mer, 4e étage dans la copropriété Le Jardin Cennelum à Bas-Cimiez. Chauffage au sol, disponible début octobre.",
  },

  // --- Ajoute tes prochaines annonces ici ---
];
