// Base de données des annonces — C'est Combien Ton Loyer ?
// Chaque groupe de 5 annonces = 1 partie du jour (jour: 1, jour: 2, etc.)
// Import via admin (node server.js) ou ajout manuel

const ANNONCES = [

  // --- Jour 1 ---
  {
    jour: 1,
    ville: "Eymoutiers",
    titre: "Eymoutiers (87120)",
    sous_titre: "Appartement · Location",
    coords: [45.738921, 1.743275],
    zoom: 16,
    tooltip: "Eymoutiers (87120)",
    loyer: 460,
    lien: "https://www.seloger.com/annonce/location/nouvelle-aquitaine/haute-vienne-87/eymoutiers-87120/26GZU8GFJLN9?serp_view=list&search=distributionTypes%3DRent%26estateTypes%3DHouse%2CApartment%26locations%3DeyJwbGFjZUlkIjoiQUQwOEZSODExMyIsInJhZGl1cyI6NDYsInBvbHlsaW5lIjoiZ31fekd5e31LfHBAYnlVYHNDbHxUZm9GaGRTfmFJfnJQZmhLfGtNYF9NZnNJbmROem1FZHdOYGFBbnZOdWtBbGJOe3ZFfHtMZ3lJbmRLX25Nan5IfXBQYGxGZ35SfHBDb3NUaHBAb25VaXBAcW5VfXBDbXNUYWxGaX5Sa35Ie3BQb2RLYW5NfXtMZ3lJbWJOe3ZFb3ZOc2tBZXdOYGFBb2ROem1FYV9NZnNJZ2hLfGtNX2JJfnJQZ29GZmRTYXNDbnxUfXBAYnlVIiwiY29vcmRpbmF0ZXMiOnsibGF0Ijo0NS45NTgzMzkzNDI2NzkyOTUsImxuZyI6Mi4xMjQyOTIzNzU4NjY2MTY2fX0%26method%3Dform#ln=classified_search_results&m=classified_search_results_classified_classified_detail_M",
    source: "SeLoger",
    badges: [
      { label: "Surface", value: "48,79 m²" },
      { label: "Pièces", value: "3 pièces · 2 ch." },
      { label: "Étage", value: "" },
      { label: "Meublé", value: "❌ Non" },
      { label: "Parking", value: "❌ Non" },
      { label: "Extérieur", value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État", value: "Entièrement rénové" },
      { label: "DPE", value: "Non communiqué" },
      { label: "Chauffage", value: "Non communiqué" },
      { label: "Exposition", value: "Non communiquée" },
      { label: "Transports", value: "Non communiqué" },
    ],
    particularites: "☀️ Lumineux",
    note: "48.79 m² · 2 chambres",
  },
  {
    jour: 1,
    ville: "Andernos-les-Bains",
    titre: "Andernos-les-Bains (33510)",
    sous_titre: "Maison · Location meublée",
    coords: [44.74769, -1.092518],
    zoom: 16,
    tooltip: "Andernos-les-Bains (33510)",
    loyer: 1400,
    lien: "https://www.seloger.com/annonce/location/nouvelle-aquitaine/gironde-33/andernos-les-bains-33510/26PNBXNEVW2E?serp_view=list&search=distributionTypes%3DRent%26estateTypes%3DHouse%2CApartment%26locations%3DeyJwbGFjZUlkIjoiQUQwOEZSMTMzNjUiLCJyYWRpdXMiOjE5LCJwb2x5bGluZSI6Im1tcXFHfHFuRnBTZmVIentAeHlHeGFCbGNHfmNDYGNGfGBEenlEdHdEbGlDZmdFenNBZG9FYFtgb0V3XFx8ZkVpdUFkd0RtakNoYERlekRqY0N1YkZoYUJvYkdwe0BreEdsU3FjSG1Tb2NIcXtAa3hHaWFCb2JHa2NDd2JGaWBEZXpEZXdEbWpDfWZFaXVBYW9FdVxcZW9FflpnZ0V6c0F1d0RsaUN9YER6eURfZENgY0Z5YUJsY0d7e0B4eUdxU2ZlSCIsImNvb3JkaW5hdGVzIjp7ImxhdCI6NDQuODE1OTUyMTY4MjUyMTgsImxuZyI6LTEuMjI2NzExMDIwODU4ODU3Nn19%26method%3Dform#ln=classified_search_results&m=classified_search_results_classified_classified_detail_M",
    source: "SeLoger",
    badges: [
      { label: "Surface", value: "110 m²" },
      { label: "Pièces", value: "4 pièces · 3 ch." },
      { label: "Étage", value: "RDC · Plain-pied" },
      { label: "Meublé", value: "✅ Oui" },
      { label: "Parking", value: "❌ Non" },
      { label: "Extérieur", value: "Jardin 650 m²" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État", value: "Entièrement rénové" },
      { label: "DPE", value: "Non communiqué" },
      { label: "Chauffage", value: "Non communiqué" },
      { label: "Exposition", value: "Non communiquée" },
      { label: "Transports", value: "Non communiqué" },
    ],
    particularites: "🔇 Calme · 🏠 Cave · 🏊 Piscine · 🔥 Poêle",
    note: "Plain-pied · 110 m² · 3 chambres · jardin 650 m² · 🏊 piscine · quartier calme",
  },

  /* SUPPRIMÉ jour 1
  {
      jour: 1,
      ville: "Andernos-les-Bains",
      titre: "Andernos-les-Bains (33510)",
      sous_titre: "Maison · Location meublée",
      coords: [44.74769, -1.092518],
      zoom: 16,
      tooltip: "Andernos-les-Bains (33510)",
      loyer: 1400,
      lien: "https://www.seloger.com/annonce/location/nouvelle-aquitaine/gironde-33/andernos-les-bains-33510/26PNBXNEVW2E?serp_view=list&search=distributionTypes%3DRent%26estateTypes%3DHouse%2CApartment%26locations%3DeyJwbGFjZUlkIjoiQUQwOEZSMTMzNjUiLCJyYWRpdXMiOjE5LCJwb2x5bGluZSI6Im1tcXFHfHFuRnBTZmVIentAeHlHeGFCbGNHfmNDYGNGfGBEenlEdHdEbGlDZmdFenNBZG9FYFtgb0V3XFx8ZkVpdUFkd0RtakNoYERlekRqY0N1YkZoYUJvYkdwe0BreEdsU3FjSG1Tb2NIcXtAa3hHaWFCb2JHa2NDd2JGaWBEZXpEZXdEbWpDfWZFaXVBYW9FdVxcZW9FflpnZ0V6c0F1d0RsaUN9YER6eURfZENgY0Z5YUJsY0d7e0B4eUdxU2ZlSCIsImNvb3JkaW5hdGVzIjp7ImxhdCI6NDQuODE1OTUyMTY4MjUyMTgsImxuZyI6LTEuMjI2NzExMDIwODU4ODU3Nn19%26method%3Dform#ln=classified_search_results&m=classified_search_results_classified_classified_detail_M",
      source: "SeLoger",
      badges: [
        { label: "Surface", value: "110 m²" },
        { label: "Pièces", value: "4 pièces · 3 ch." },
        { label: "Étage", value: "" },
        { label: "Meublé", value: "✅ Oui" },
        { label: "Parking", value: "❌ Non" },
        { label: "Extérieur", value: "Jardin" },
        { label: "Année construction", value: "Non communiquée" },
        { label: "État", value: "Entièrement rénové" },
        { label: "DPE", value: "Non communiqué" },
        { label: "Chauffage", value: "Non communiqué" },
        { label: "Exposition", value: "Non communiquée" },
        { label: "Transports", value: "Non communiqué" },
      ],
      particularites: "🔇 Calme · 🏠 Cave · 🏊 Piscine",
      note: "",
    },
  */
  // { jour: 1, ville: "Paris", coords: [48.8566, 2.3522], zoom: 15, tooltip: "Paris · Marais", loyer: 1800, lien: "https://...", source: "Bien'ici", badges: [ ... ], particularites: "", note: "" },

];
