// Base de données des annonces — C'est Combien Ton Loyer ?
// Chaque groupe de 5 annonces = 1 partie du jour (jour: 1, jour: 2, etc.)
// Import via admin (node server.js) ou ajout manuel

const ANNONCES = [

  // --- Jour 1 ---
  {
    id: 1,
    jour: 1,
    ville: "Nice",
    titre: "Nice (06000)",
    sous_titre: "Appartement · Location meublée",
    coords: [43.685989, 7.237476],
    zoom: 16,
    tooltip: "Nice (06000)",
    loyer: 1500,
    lien: "https://www.pap.fr/annonces/appartement-nice-06000-r465302794",
    source: "PAP",
    badges: [
      { label: "Surface", value: "38 m²" },
      { label: "Pièces", value: "2 pièces · 1 ch." },
      { label: "Étage", value: "1e · sans ascenseur" },
      { label: "Meublé", value: "✅ Oui" },
      { label: "Parking", value: "❌ Non" },
      { label: "Extérieur", value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État", value: "Entretenu" },
      { label: "DPE", value: "Non communiqué" },
      { label: "Chauffage", value: "Non communiqué" },
      { label: "Exposition", value: "Non communiquée" },
      { label: "Transports", value: "Non communiqué" },
    ],
    particularites: "",
    note: "Appartement 2 pièces de 38 m² à Nice (06000), situé sur la Promenade des Anglais avec accès à la mer et tramway proche. Appartement entièrement réaménagé avec climatisation, TV, Wi-Fi et cuisine équipée.",
  },

  /* SUPPRIMÉ jour 1
  {
      jour: 1,
      ville: "Nice",
      titre: "Nice (06000)",
      sous_titre: "Appartement · Location meublée",
      coords: [43.685989, 7.237476],
      zoom: 16,
      tooltip: "Nice (06000)",
      loyer: 1500,
      lien: "https://www.pap.fr/annonces/appartement-nice-06000-r465302794",
      source: "PAP",
      badges: [
        { label: "Surface", value: "38 m²" },
        { label: "Pièces", value: "2 pièces · 1 ch." },
        { label: "Étage", value: "1e · sans ascenseur" },
        { label: "Meublé", value: "✅ Oui" },
        { label: "Parking", value: "❌ Non" },
        { label: "Extérieur", value: "❌ Aucun" },
        { label: "Année construction", value: "Non communiquée" },
        { label: "État", value: "Entretenu" },
        { label: "DPE", value: "Non communiqué" },
        { label: "Chauffage", value: "Non communiqué" },
        { label: "Exposition", value: "Non communiquée" },
        { label: "Transports", value: "Non communiqué" },
      ],
      particularites: "🏠 Cave · 🛋️ Meublé · ❄️ Climatisation",
      note: "1e étage · 38 m² · 1 chambre",
    },
  */

  /* SUPPRIMÉ jour 1
  {
      jour: 1,
      ville: "Nice",
      titre: "Nice (06000)",
      sous_titre: "Appartement · Location meublée",
      coords: [48.851855, 2.293363],
      zoom: 16,
      tooltip: "Nice (06000)",
      loyer: 1500,
      lien: "https://www.pap.fr/annonces/appartement-nice-06000-r465302794",
      source: "PAP",
      badges: [
        { label: "Surface", value: "38 m²" },
        { label: "Pièces", value: "2 pièces · 1 ch." },
        { label: "Étage", value: "1e · sans ascenseur" },
        { label: "Meublé", value: "✅ Oui" },
        { label: "Parking", value: "❌ Non" },
        { label: "Extérieur", value: "❌ Aucun" },
        { label: "Année construction", value: "Non communiquée" },
        { label: "État", value: "Entretenu" },
        { label: "DPE", value: "Non communiqué" },
        { label: "Chauffage", value: "Non communiqué" },
        { label: "Exposition", value: "Non communiquée" },
        { label: "Transports", value: "Non communiqué" },
      ],
      particularites: "🏠 Cave · 🛋️ Meublé · ❄️ Climatisation",
      note: "1e étage · 38 m² · 1 chambre",
    },
  */
  {
    id: 2,
    jour: 1,
    ville: "Paris 15e",
    titre: "Dupleix - Motte Picquet, 4p · 100.43m²",
    sous_titre: "Appartement · Paris 15e · 75015",
    coords: [48.85186, 2.29336],
    zoom: 16,
    tooltip: "Dupleix - Motte Picquet, 4p · 100.43m²",
    loyer: 9000,
    lien: "https://www.bienici.com/annonce/location/paris-15e/appartement/4pieces/apimo-86969257?q=%2Frecherche%2Flocation%2Ffrance%3Fprix-min%3D3000",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "100.43 m²" },
      { label: "Pièces", value: "4 pièces · 2 ch." },
      { label: "Étage", value: "9e · avec ascenseur" },
      { label: "Meublé", value: "✅ Oui" },
      { label: "Parking", value: "❌ Non" },
      { label: "Extérieur", value: "✅ Oui, 2 terrasses" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État", value: "✨ Rénové" },
      { label: "DPE", value: "E" },
      { label: "Chauffage", value: "Radiateur Electrique Individuel" },
      { label: "Exposition", value: "Non communiquée" },
      { label: "Transports", value: "Métro" },
    ],
    particularites: "9e étage · 🛗 Ascenseur · Chauffage : Radiateur Electrique Individuel · Vue Tour Eiffel",
    note: "9ème étage, immeuble sécurisé, 100m² appartement, ascenseur, récentement rénové par un architecte de renom, climatisé, 2 terrasses, 1 chambre en suite et 1 chambre/bureau, vue Tour Eiffel, Invalides, proximité gardien, interphone, digicode, local vélos, 2 parkings, cave, chauffage et eau chaude individuels électriques, disponible immédiatement, Bail CIV.",
  },
  {
    id: 3,
    jour: 1,
    ville: "Antibes",
    titre: "Rabiac - Carriat - Les Semboules - Les Brusquets, 6p · 180.83m²",
    sous_titre: "Maison · Antibes · 06600",
    coords: [43.59668, 7.07326],
    zoom: 16,
    tooltip: "Rabiac - Carriat - Les Semboules - Les Brusquets",
    loyer: 3990,
    lien: "https://www.bienici.com/annonce/location/antibes/maison/6pieces/citya-immobilier-1171-GES81660008-74?q=%2Frecherche%2Flocation%2Ffrance%3Fprix-min%3D3000",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "180.83 m²" },
      { label: "Pièces", value: "6 pièces · 4 ch." },
      { label: "Étage", value: "Non communiqué" },
      { label: "Meublé", value: "✅ Oui" },
      { label: "Parking", value: "❌ Non" },
      { label: "Extérieur", value: "Jardin" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "DPE", value: "C" },
      { label: "Chauffage", value: "Electrique Individuel" },
      { label: "Exposition", value: "Sud" },
      { label: "État", value: "Non communiqué" },
      { label: "Transports", value: "Non communiqué" },
    ],
    particularites: "🪣 Cave · ☀️ Exposition Sud",
    note: "Villa T6, 180m², Antibes center. Bright living spaces, spacious living room, fully equipped kitchen. 4 climate-controlled bedrooms, private parental suite with terrace. Mezzanine office with sea view. Landscaped garden, pool, garage, exterior parking, laundry room. South-facing, sea view, calm neighborhood.",
  },

  /* SUPPRIMÉ jour 1
  {
      jour: 1,
      ville: "Antibes",
      titre: "Rabiac - Carriat - Les Semboules - Les Brusquets, Antibes (06600)",
      sous_titre: "Maison · Location meublée",
      coords: [43.596683, 7.073261],
      zoom: 16,
      tooltip: "Rabiac - Carriat - Les Semboules - Les Brusquets, Antibes (06600)",
      loyer: 3990,
      lien: "https://www.bienici.com/annonce/location/antibes/maison/6pieces/citya-immobilier-1171-GES81660008-74?q=%2Frecherche%2Flocation%2Ffrance%3Fprix-min%3D3000",
      source: "Bien'ici",
      badges: [
        { label: "Surface", value: "180.83 m²" },
        { label: "Pièces", value: "6 pièces · 4 ch." },
        { label: "Étage", value: "" },
        { label: "Meublé", value: "✅ Oui" },
        { label: "Parking", value: "❌ Non" },
        { label: "Extérieur", value: "Jardin" },
        { label: "Année construction", value: "Non communiquée" },
        { label: "État", value: "Entretenu" },
        { label: "DPE", value: "C · GES A" },
        { label: "Chauffage", value: "Electrique Individuel" },
        { label: "Exposition", value: "Non communiquée" },
        { label: "Transports", value: "Non communiqué" },
      ],
      particularites: "🔇 Calme · 🏊 Piscine · 🛋️ Meublé",
      note: "À LOUER Nichée au cœur d'Antibes, cette somptueuse villa T6 de 180 m² habitables, édifiée sur un terrain de 1 500 m², offre un cadre de vie exceptionnel alliant élégance, confort et sérénité. Dès l'entrée, vous découvrirez des espaces de vie baignés de lumière.",
    },
  */
  {
    id: 4,
    jour: 1,
    ville: "Eymoutiers",
    titre: "Eymoutiers (87120)",
    sous_titre: "Appartement · Location",
    coords: [45.738921, 1.743275],
    zoom: 16,
    tooltip: "Eymoutiers (87120)",
    loyer: 460,
    lien: "https://www.seloger.com/annonce/location/nouvelle-aquitaine/haute-vienne-87/eymoutiers-87120/26GZU8GFJLN9?serp_view=list&search=distributionTypes%3DRent%26estateTypes%3DHouse%2CApartment%26locations%3DeyJwbGFjZUlkIjoiQUQwOEZSODExMyIsInJhZGl1cyI6NDYsInBvbHlsaW5lIjoiZ31fekd5e31LfHBAYnlVYHNDbHxUZm9GaGRTfmFJfnJQZmhLfGtNYF9NZnNJbmROem1FZHdOYGFBbnZOdWtBbGJOe3ZFfHtMZ3lJbmRLX25Nan5IfXBQYGxGZ35SfHBDb3NUaHBAb25VaXBAcW5VfXBDbXNUYWxGaX5Sa35Ie3BQb2RLYW5NfXtMZ3lJbWJOe3ZFb3ZOc2tBZXdOYGFBb2ROem1FYV9NZnNJZ2hLfGtNX2JJfnJQZ29GZmRTYXNDbnxUfXBAYnlVIiwiY29vcmRpbmF0ZXMiOnsibGF0Ijo0NS45NTgzMzkzNDI2NzkyOTUsImxuZyI6Mi4xMjQyOTIzNzU4NjY2MTY2fX0%26method%3Dform#ln=classified_search_results&m=classified_search_results_classified_classified_detail_M",
    source: "SeLoger",
    badges: [
      { label: "Surface", value: "48,79 m²" },
      { label: "Pièces", value: "3 pièces · 2 ch." },
      { label: "Étage", value: "" },
      { label: "Meublé", value: "❌ Non" },
      { label: "Parking", value: "❌ Non" },
      { label: "Extérieur", value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État", value: "Entièrement rénové" },
      { label: "DPE", value: "Non communiqué" },
      { label: "Chauffage", value: "Non communiqué" },
      { label: "Exposition", value: "Non communiquée" },
      { label: "Transports", value: "Non communiqué" },
    ],
    particularites: "☀️ Lumineux",
    note: "48.79 m² · 2 chambres",
  },
  {
    id: 5,
    jour: 1,
    ville: "Andernos-les-Bains",
    titre: "Andernos-les-Bains (33510)",
    sous_titre: "Maison · Location meublée",
    coords: [44.74769, -1.092518],
    zoom: 16,
    tooltip: "Andernos-les-Bains (33510)",
    loyer: 1400,
    lien: "https://www.seloger.com/annonce/location/nouvelle-aquitaine/gironde-33/andernos-les-bains-33510/26PNBXNEVW2E?serp_view=list&search=distributionTypes%3DRent%26estateTypes%3DHouse%2CApartment%26locations%3DeyJwbGFjZUlkIjoiQUQwOEZSMTMzNjUiLCJyYWRpdXMiOjE5LCJwb2x5bGluZSI6Im1tcXFHfHFuRnBTZmVIentAeHlHeGFCbGNHfmNDYGNGfGBEenlEdHdEbGlDZmdFenNBZG9FYFtgb0V3XFx8ZkVpdUFkd0RtakNoYERlekRqY0N1YkZoYUJvYkdwe0BreEdsU3FjSG1Tb2NIcXtAa3hHaWFCb2JHa2NDd2JGaWBEZXpEZXdEbWpDfWZFaXVBYW9FdVxcZW9FflpnZ0V6c0F1d0RsaUN9YER6eURfZENgY0Z5YUJsY0d7e0B4eUdxU2ZlSCIsImNvb3JkaW5hdGVzIjp7ImxhdCI6NDQuODE1OTUyMTY4MjUyMTgsImxuZyI6LTEuMjI2NzExMDIwODU4ODU3Nn19%26method%3Dform#ln=classified_search_results&m=classified_search_results_classified_classified_detail_M",
    source: "SeLoger",
    badges: [
      { label: "Surface", value: "110 m²" },
      { label: "Pièces", value: "4 pièces · 3 ch." },
      { label: "Étage", value: "RDC · Plain-pied" },
      { label: "Meublé", value: "✅ Oui" },
      { label: "Parking", value: "❌ Non" },
      { label: "Extérieur", value: "Jardin 650 m²" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État", value: "Entièrement rénové" },
      { label: "DPE", value: "Non communiqué" },
      { label: "Chauffage", value: "Non communiqué" },
      { label: "Exposition", value: "Non communiquée" },
      { label: "Transports", value: "Non communiqué" },
    ],
    particularites: "🔇 Calme · 🏠 Cave · 🏊 Piscine · 🔥 Poêle",
    note: "Plain-pied · 110 m² · 3 chambres · jardin 650 m² · 🏊 piscine · quartier calme",
  },

  /* SUPPRIMÉ jour 1
  {
      jour: 1,
      ville: "Andernos-les-Bains",
      titre: "Andernos-les-Bains (33510)",
      sous_titre: "Maison · Location meublée",
      coords: [44.74769, -1.092518],
      zoom: 16,
      tooltip: "Andernos-les-Bains (33510)",
      loyer: 1400,
      lien: "https://www.seloger.com/annonce/location/nouvelle-aquitaine/gironde-33/andernos-les-bains-33510/26PNBXNEVW2E?serp_view=list&search=distributionTypes%3DRent%26estateTypes%3DHouse%2CApartment%26locations%3DeyJwbGFjZUlkIjoiQUQwOEZSMTMzNjUiLCJyYWRpdXMiOjE5LCJwb2x5bGluZSI6Im1tcXFHfHFuRnBTZmVIentAeHlHeGFCbGNHfmNDYGNGfGBEenlEdHdEbGlDZmdFenNBZG9FYFtgb0V3XFx8ZkVpdUFkd0RtakNoYERlekRqY0N1YkZoYUJvYkdwe0BreEdsU3FjSG1Tb2NIcXtAa3hHaWFCb2JHa2NDd2JGaWBEZXpEZXdEbWpDfWZFaXVBYW9FdVxcZW9FflpnZ0V6c0F1d0RsaUN9YER6eURfZENgY0Z5YUJsY0d7e0B4eUdxU2ZlSCIsImNvb3JkaW5hdGVzIjp7ImxhdCI6NDQuODE1OTUyMTY4MjUyMTgsImxuZyI6LTEuMjI2NzExMDIwODU4ODU3Nn19%26method%3Dform#ln=classified_search_results&m=classified_search_results_classified_classified_detail_M",
      source: "SeLoger",
      badges: [
        { label: "Surface", value: "110 m²" },
        { label: "Pièces", value: "4 pièces · 3 ch." },
        { label: "Étage", value: "" },
        { label: "Meublé", value: "✅ Oui" },
        { label: "Parking", value: "❌ Non" },
        { label: "Extérieur", value: "Jardin" },
        { label: "Année construction", value: "Non communiquée" },
        { label: "État", value: "Entièrement rénové" },
        { label: "DPE", value: "Non communiqué" },
        { label: "Chauffage", value: "Non communiqué" },
        { label: "Exposition", value: "Non communiquée" },
        { label: "Transports", value: "Non communiqué" },
      ],
      particularites: "🔇 Calme · 🏠 Cave · 🏊 Piscine",
      note: "",
    },
  */

  // --- Jour 2 ---
  {
    id: 6,
    jour: 2,
    ville: "Saint-Affrique",
    titre: "Saint-Affrique, Saint-Affrique (12400)",
    sous_titre: "Appartement · Location vide",
    coords: [43.953875, 2.891336],
    zoom: 16,
    tooltip: "Saint-Affrique, Saint-Affrique (12400)",
    loyer: 661,
    lien: "https://www.bienici.com/annonce/location/saint-affrique/appartement/5pieces/immo-facile-61478448?q=%2Frecherche%2Flocation%2Ffrance%3Fcamera%3D15_2.5733003_44.3511276_0_0",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "89 m²" },
      { label: "Pièces", value: "5 pièces · 4 ch." },
      { label: "Étage", value: "3e" },
      { label: "Meublé", value: "❌ Non" },
      { label: "Parking", value: "❌ Non" },
      { label: "Extérieur", value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État", value: "Entretenu" },
      { label: "DPE", value: "C · GES A" },
      { label: "Chauffage", value: "Non communiqué" },
      { label: "Exposition", value: "Non communiquée" },
      { label: "Transports", value: "Non communiqué" },
    ],
    particularites: "🏠 Cave",
    note: "3e étage · 89 m² · 4 chambres",
  },
  {
    id: 7,
    jour: 2,
    ville: "Viviers-du-Lac",
    titre: "Viviers-du-Lac (73420)",
    sous_titre: "Appartement · Location meublée",
    coords: [45.6485, 5.90567],
    zoom: 16,
    tooltip: "Viviers-du-Lac (73420)",
    loyer: 1132,
    lien: "https://www.seloger.com/annonce/location/auvergne-rhone-alpes/savoie-73/viviers-du-lac-73420/26NWT21MCAUT?ln=classified_search_results_map&serp_view=map&search=distributionTypes%3DRent%26estateTypes%3DHouse%2CApartment%26locations%3DeyJwbGFjZUlkIjoiQUQwOEZSODExMyIsInJhZGl1cyI6NDYsInBvbHlsaW5lIjoiZ31fekd5e31LfHBAYnlVYHNDbHxUZm9GaGRTfmFJfnJQZmhLfGtNYF9NZnNJbmROem1FZHdOYGFBbnZOdWtBbGJOe3ZFfHtMZ3lJbmRLX25Nan5IfXBQYGxGZ35SfHBDb3NUaHBAb25VaXBAcW5VfXBDbXNUYWxGaX5Sa35Ie3BQb2RLYW5NfXtMZ3lJbWJOe3ZFb3ZOc2tBZXdOYGFBb2ROem1FYV9NZnNJZ2hLfGtNX2JJfnJQZ29GZmRTYXNDbnxUfXBAYnlVIiwiY29vcmRpbmF0ZXMiOnsibGF0Ijo0NS45NTgzMzkzNDI2NzkyOTUsImxuZyI6Mi4xMjQyOTIzNzU4NjY2MTY2fX0%26method%3Dform#ln=classified_search_results_map&m=classified_search_results_map_classified_classified_detail_M",
    source: "SeLoger",
    badges: [
      { label: "Surface", value: "62 m²" },
      { label: "Pièces", value: "3 pièces · 2 ch." },
      { label: "Étage", value: "1e · avec ascenseur" },
      { label: "Meublé", value: "✅ Oui" },
      { label: "Parking", value: "✅ Oui" },
      { label: "Extérieur", value: "Balcon" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État", value: "Entretenu" },
      { label: "DPE", value: "Non communiqué" },
      { label: "Chauffage", value: "Chauffage individuel: Radiateur Sources" },
      { label: "Exposition", value: "ouest Voir les 12 caractéristi" },
      { label: "Transports", value: "Non communiqué" },
    ],
    particularites: "🏠 Cave",
    note: "Appartement 3 pièces, 2 chambres, 62 m², 1er étage à Viviers-du-Lac (73420). Infrastructure : parking privé, balcon, cuisine intégrée, WC séparés, pas d'ascenseur. Proximité commerces/transports.",
  },
  {
    id: 8,
    jour: 2,
    ville: "Lorient",
    titre: "Lorient (56100)",
    sous_titre: "Studio · Location meublée",
    coords: [47.747734, -3.366091],
    zoom: 16,
    tooltip: "Lorient (56100)",
    loyer: 485,
    lien: "https://www.seloger.com/annonce/location/bretagne/morbihan-56/lorient-56100/26VMEHPDKDW9?ln=classified_search_results_map&serp_view=map&search=distributionTypes%3DRent%26estateTypes%3DHouse%2CApartment%26locations%3DeyJwbGFjZUlkIjoiQUQwOEZSODExMyIsInJhZGl1cyI6NDYsInBvbHlsaW5lIjoiZ31fekd5e31LfHBAYnlVYHNDbHxUZm9GaGRTfmFJfnJQZmhLfGtNYF9NZnNJbmROem1FZHdOYGFBbnZOdWtBbGJOe3ZFfHtMZ3lJbmRLX25Nan5IfXBQYGxGZ35SfHBDb3NUaHBAb25VaXBAcW5VfXBDbXNUYWxGaX5Sa35Ie3BQb2RLYW5NfXtMZ3lJbWJOe3ZFb3ZOc2tBZXdOYGFBb2ROem1FYV9NZnNJZ2hLfGtNX2JJfnJQZ29GZmRTYXNDbnxUfXBAYnlVIiwiY29vcmRpbmF0ZXMiOnsibGF0Ijo0NS45NTgzMzkzNDI2NzkyOTUsImxuZyI6Mi4xMjQyOTIzNzU4NjY2MTY2fX0%26method%3Dform#ln=classified_search_results_map&m=classified_search_results_map_classified_classified_detail_M",
    source: "SeLoger",
    badges: [
      { label: "Surface", value: "19 m²" },
      { label: "Pièces", value: "1 pièce" },
      { label: "Étage", value: "" },
      { label: "Meublé", value: "✅ Oui" },
      { label: "Parking", value: "❌ Non" },
      { label: "Extérieur", value: "Balcon" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État", value: "Entretenu" },
      { label: "DPE", value: "Non communiqué" },
      { label: "Chauffage", value: "Non communiqué" },
      { label: "Exposition", value: "Non communiquée" },
      { label: "Transports", value: "Non communiqué" },
    ],
    particularites: "",
    note: "Studio à louer, étudiant, Kervaric-Kerichant-Lanveur, Lorient. Proximité université, commerce, transports.  Résidence étudiante Campus Horizon, Lorient. Proximité université, commerce, transports. Studios meublés avec connexion internet.",
  },
  {
    id: 9,
    jour: 2,
    ville: "Reims",
    titre: "Reims (51100)",
    sous_titre: "Studio · Location",
    coords: [49.246011, 4.017983],
    zoom: 16,
    tooltip: "Reims (51100)",
    loyer: 395,
    lien: "https://www.pap.fr/annonces/appartement-reims-51100-r416701492",
    source: "PAP",
    badges: [
      { label: "Surface", value: "17 m²" },
      { label: "Pièces", value: "1 pièce" },
      { label: "Étage", value: "1e · sans ascenseur" },
      { label: "Meublé", value: "N/A" },
      { label: "Parking", value: "❌ Non" },
      { label: "Extérieur", value: "❌ Aucun" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État", value: "Entretenu" },
      { label: "DPE", value: "Non communiqué" },
      { label: "Chauffage", value: "Non communiqué" },
      { label: "Exposition", value: "Non communiquée" },
      { label: "Transports", value: "🚋 Tram · 🚌 Bus" },
    ],
    particularites: "",
    note: "Studio étudiant, 17 m², 1er étage, Quartier Courlancy, Reims (51100). Proximité IUT, fac de médecine, transport (tramway, bus). Studio avec cuisine et salle de bains. Immeuble raccordé à la fibre optique.",
  },
  {
    id: 10,
    jour: 3,
    ville: "Bouxwiller",
    titre: "Bouxwiller (67330)",
    sous_titre: "Maison · Location",
    coords: [48.8255, 7.480029],
    zoom: 16,
    tooltip: "Bouxwiller (67330)",
    loyer: 1200,
    lien: "https://www.leboncoin.fr/ad/locations/3273336096",
    source: "LeBonCoin",
    badges: [
      { label: "Surface", value: "136 m²" },
      { label: "Pièces", value: "5 pièces · 3 ch." },
      { label: "Étage", value: "2e" },
      { label: "Meublé", value: "❌ Non" },
      { label: "Parking", value: "❌ Non" },
      { label: "Extérieur", value: "Jardin" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État", value: "Entretenu" },
      { label: "DPE", value: "Non communiqué" },
      { label: "Chauffage", value: "individuel au gaz" },
      { label: "Exposition", value: "Non communiquée" },
      { label: "Transports", value: "Non communiqué" },
    ],
    particularites: "🏠 Cave",
    note: "Maison individuelle de 136 m² à louer à Bouxwiller (67330), offrant 5 pièces, cuisine équipée, salon, bureau, jardin, et 2 salles de bain. Proximité des commerces et transports.",
  },
  {
    id: 11,
    jour: 2,
    ville: "Rodez",
    titre: "Centre historique - Vieux-Rodez, Rodez (12000)",
    sous_titre: "Appartement · Location vide",
    coords: [44.351385, 2.573053],
    zoom: 16,
    tooltip: "Centre historique - Vieux-Rodez, Rodez (12000)",
    loyer: 880,
    lien: "https://www.bienici.com/annonce/location/rodez/appartement/4pieces/hektor-cabrouergat-1495?q=%2Frecherche%2Flocation%2Ffrance%3Fcamera%3D15_2.5733003_44.3511276_0_0",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "116.78 m²" },
      { label: "Pièces", value: "4 pièces · 3 ch." },
      { label: "Étage", value: "2e" },
      { label: "Meublé", value: "❌ Non" },
      { label: "Parking", value: "✅ Oui" },
      { label: "Extérieur", value: "❌ Aucun" },
      { label: "Année construction", value: "1975" },
      { label: "État", value: "Entretenu" },
      { label: "DPE", value: "B · GES A" },
      { label: "Chauffage", value: "sol électrique collectif" },
      { label: "Exposition", value: "Non communiquée" },
      { label: "Transports", value: "Non communiqué" },
    ],
    particularites: "🏠 Cave",
    note: "2e étage · 116.78 m² · 3 chambres · 1 sdb · construit 1975 · ascenseur · cave",
  },

  /* SUPPRIMÉ jour 2
  {
      jour: 2,
      ville: "Viviers-du-Lac Viviers-du-Lac",
      titre: "Viviers-du-Lac (73420)",
      sous_titre: "Appartement · Location meublée",
      coords: [43.685989, 7.237476],
      zoom: 16,
      tooltip: "Viviers-du-Lac (73420)",
      loyer: 1132,
      lien: "https://www.seloger.com/annonce/location/auvergne-rhone-alpes/savoie-73/viviers-du-lac-73420/26NWT21MCAUT?ln=classified_search_results_map&serp_view=map&search=distributionTypes%3DRent%26estateTypes%3DHouse%2CApartment%26locations%3DeyJwbGFjZUlkIjoiQUQwOEZSODExMyIsInJhZGl1cyI6NDYsInBvbHlsaW5lIjoiZ31fekd5e31LfHBAYnlVYHNDbHxUZm9GaGRTfmFJfnJQZmhLfGtNYF9NZnNJbmROem1FZHdOYGFBbnZOdWtBbGJOe3ZFfHtMZ3lJbmRLX25Nan5IfXBQYGxGZ35SfHBDb3NUaHBAb25VaXBAcW5VfXBDbXNUYWxGaX5Sa35Ie3BQb2RLYW5NfXtMZ3lJbWJOe3ZFb3ZOc2tBZXdOYGFBb2ROem1FYV9NZnNJZ2hLfGtNX2JJfnJQZ29GZmRTYXNDbnxUfXBAYnlVIiwiY29vcmRpbmF0ZXMiOnsibGF0Ijo0NS45NTgzMzkzNDI2NzkyOTUsImxuZyI6Mi4xMjQyOTIzNzU4NjY2MTY2fX0%26method%3Dform#ln=classified_search_results_map&m=classified_search_results_map_classified_classified_detail_M",
      source: "SeLoger",
      badges: [
        { label: "Surface", value: "62 m²" },
        { label: "Pièces", value: "3 pièces · 2 ch." },
        { label: "Étage", value: "1e · avec ascenseur" },
        { label: "Meublé", value: "✅ Oui" },
        { label: "Parking", value: "✅ Oui" },
        { label: "Extérieur", value: "Balcon" },
        { label: "Année construction", value: "Non communiquée" },
        { label: "État", value: "Entretenu" },
        { label: "DPE", value: "Non communiqué" },
        { label: "Chauffage", value: "Chauffage individuel: Radiateur Sources" },
        { label: "Exposition", value: "ouest Voir les 12 caractéristi" },
        { label: "Transports", value: "Non communiqué" },
      ],
      particularites: "🏠 Cave",
      note: "Appartement 3 pièces, 2 chambres, 62m², 1er étage à Viviers-du-Lac (73420). Inclut forfait de charges. Parking privé, balcon. Proximité commerce et transports.",
    },
  */

  /* SUPPRIMÉ jour 2
  {
      jour: 2,
      ville: "Lorient",
      titre: "Lorient (56100)",
      sous_titre: "Studio · Location meublée",
      coords: [43.685989, 7.237476],
      zoom: 16,
      tooltip: "Lorient (56100)",
      loyer: 485,
      lien: "https://www.seloger.com/annonce/location/bretagne/morbihan-56/lorient-56100/26VMEHPDKDW9?ln=classified_search_results_map&serp_view=map&search=distributionTypes%3DRent%26estateTypes%3DHouse%2CApartment%26locations%3DeyJwbGFjZUlkIjoiQUQwOEZSODExMyIsInJhZGl1cyI6NDYsInBvbHlsaW5lIjoiZ31fekd5e31LfHBAYnlVYHNDbHxUZm9GaGRTfmFJfnJQZmhLfGtNYF9NZnNJbmROem1FZHdOYGFBbnZOdWtBbGJOe3ZFfHtMZ3lJbmRLX25Nan5IfXBQYGxGZ35SfHBDb3NUaHBAb25VaXBAcW5VfXBDbXNUYWxGaX5Sa35Ie3BQb2RLYW5NfXtMZ3lJbWJOe3ZFb3ZOc2tBZXdOYGFBb2ROem1FYV9NZnNJZ2hLfGtNX2JJfnJQZ29GZmRTYXNDbnxUfXBAYnlVIiwiY29vcmRpbmF0ZXMiOnsibGF0Ijo0NS45NTgzMzkzNDI2NzkyOTUsImxuZyI6Mi4xMjQyOTIzNzU4NjY2MTY2fX0%26method%3Dform#ln=classified_search_results_map&m=classified_search_results_map_classified_classified_detail_M",
      source: "SeLoger",
      badges: [
        { label: "Surface", value: "19 m²" },
        { label: "Pièces", value: "1 pièce" },
        { label: "Étage", value: "1e · sans ascenseur" },
        { label: "Meublé", value: "✅ Oui" },
        { label: "Parking", value: "❌ Non" },
        { label: "Extérieur", value: "Balcon" },
        { label: "Année construction", value: "Non communiquée" },
        { label: "État", value: "Entretenu" },
        { label: "DPE", value: "Non communiqué" },
        { label: "Chauffage", value: "Non communiqué" },
        { label: "Exposition", value: "Non communiquée" },
        { label: "Transports", value: "Non communiqué" },
      ],
      particularites: "",
      note: "Studio à louer pour étudiants - Résidence Campus Horizon, Lorient. Proche campus universitaire de Lanveur, commerces, et transports. Studio meublé avec cuisine, salle de bain privative, et internet haut débit.",
    },
  */

  /* SUPPRIMÉ jour 2
  {
          jour: 2,
          ville: "Reims",
          titre: "Reims (51100)",
          sous_titre: "Studio · Location",
          coords: [43.685989, 7.237476],
          zoom: 16,
          tooltip: "Reims (51100)",
          loyer: 395,
          lien: "https://www.pap.fr/annonces/appartement-reims-51100-r416701492",
          source: "PAP",
          badges: [
            { label: "Surface", value: "17 m²" },
            { label: "Pièces", value: "1 pièce" },
            { label: "Étage", value: "1e · sans ascenseur" },
            { label: "Meublé", value: "N/A" },
            { label: "Parking", value: "❌ Non" },
            { label: "Extérieur", value: "❌ Aucun" },
            { label: "Année construction", value: "Non communiquée" },
            { label: "État", value: "Entretenu" },
            { label: "DPE", value: "Non communiqué" },
            { label: "Chauffage", value: "Non communiqué" },
            { label: "Exposition", value: "Non communiquée" },
            { label: "Transports", value: "🚋 Tram · 🚌 Bus" },
          ],
          particularites: "",
          note: "Studio étudiant, 17m² dans le quartier Courlancy de Reims (51100). Proche de l'IUT, faculté de médecine, transports en commun (tramway, bus). Studio avec cuisine, salle de bains et wc. Immeuble raccordé à la fibre optique.",
        },
  */

  /* SUPPRIMÉ jour 2
  {
      jour: 2,
      ville: "Reims",
      titre: "Reims (51100)",
      sous_titre: "Studio · Location",
      coords: [43.685989, 7.237476],
      zoom: 16,
      tooltip: "Reims (51100)",
      loyer: 395,
      lien: "https://www.pap.fr/annonces/appartement-reims-51100-r416701492",
      source: "PAP",
      badges: [
        { label: "Surface", value: "17 m²" },
        { label: "Pièces", value: "1 pièce" },
        { label: "Étage", value: "1e · sans ascenseur" },
        { label: "Meublé", value: "N/A" },
        { label: "Parking", value: "❌ Non" },
        { label: "Extérieur", value: "❌ Aucun" },
        { label: "Année construction", value: "Non communiquée" },
        { label: "État", value: "Entretenu" },
        { label: "DPE", value: "Non communiqué" },
        { label: "Chauffage", value: "Non communiqué" },
        { label: "Exposition", value: "Non communiquée" },
        { label: "Transports", value: "🚋 Tram · 🚌 Bus" },
      ],
      particularites: "",
      note: "Studio étudiant, 17m² dans le quartier Courlancy de Reims (51100). Proche de l'IUT, faculté de médecine, transports en commun (tramway, bus). Studio avec cuisine, salle de bains et wc. Immeuble raccordé à la fibre optique. Loyer compris 395 €/mois. Contactez le propriétaire : 06 17 63 25 81 ou 03 26 03 00 63.",
    },
  */


  // --- Jour 3 ---
  {
    id: 15,
    jour: 3,
    ville: "Orléans",
    titre: "Orléans (45000)",
    sous_titre: "Appartement · Location meublée",
    coords: [47.902734, 1.908607],
    zoom: 16,
    tooltip: "Orléans (45000)",
    loyer: 1330,
    lien: "https://www.seloger.com/annonce/location/centre-val-de-loire/loiret-45/orleans-45000/26DM25VNNUDN?ln=classified_search_results_map&serp_view=map&search=distributionTypes%3DRent%26estateTypes%3DHouse%2CApartment%26locations%3DeyJwbGFjZUlkIjoiQUQwOEZSODExMyIsInJhZGl1cyI6NDYsInBvbHlsaW5lIjoiZ31fekd5e31LfHBAYnlVYHNDbHxUZm9GaGRTfmFJfnJQZmhLfGtNYF9NZnNJbmROem1FZHdOYGFBbnZOdWtBbGJOe3ZFfHtMZ3lJbmRLX25Nan5IfXBQYGxGZ35SfHBDb3NUaHBAb25VaXBAcW5VfXBDbXNUYWxGaX5Sa35Ie3BQb2RLYW5NfXtMZ3lJbWJOe3ZFb3ZOc2tBZXdOYGFBb2ROem1FYV9NZnNJZ2hLfGtNX2JJfnJQZ29GZmRTYXNDbnxUfXBAYnlVIiwiY29vcmRpbmF0ZXMiOnsibGF0Ijo0NS45NTgzMzkzNDI2NzkyOTUsImxuZyI6Mi4xMjQyOTIzNzU4NjY2MTY2fX0%26method%3Dform#ln=classified_search_results_map&m=classified_search_results_map_classified_classified_detail_M",
    source: "SeLoger",
    badges: [
      { label: "Surface", value: "71 m²" },
      { label: "Pièces", value: "3 pièces · 2 ch." },
      { label: "Étage", value: "1e · avec ascenseur" },
      { label: "Meublé", value: "✅ Oui" },
      { label: "Parking", value: "Non" },
      { label: "Extérieur", value: "Non" },
      { label: "Année construction", value: "1900" },
      { label: "État", value: "Entretenu" },
      { label: "DPE", value: "Non communiqué" },
      { label: "Chauffage", value: "individuel par radiateurs" },
      { label: "Exposition", value: "Nord/Sud apporte une lumière a" },
      { label: "Transports", value: "Non communiqué" },
    ],
    particularites: "🏠 Cave · 🔥 Cheminée",
    note: "Appartement meublé de 3 pièces dans un immeuble de 1900 à Orléans (45000). Situé au 1er étage, avec parquet, cheminées et lumière Nord/Sud. Proche écoles et lieux de travail. Amenagements pratiques, double vitrage, chauffage individuel, fibre optique et interphone.",
  },
  {
    id: 14,
    jour: 3,
    ville: "Chamalières",
    titre: "Royat, Chamalières (63400)",
    sous_titre: "Appartement · Location meublée",
    coords: [45.765861, 3.060808],
    zoom: 16,
    tooltip: "Royat, Chamalières (63400)",
    loyer: 1480,
    lien: "https://www.bienici.com/annonce/location/chamalieres/appartement/4pieces/citya-immobilier-33843621500044-GES97840222-702?q=%2Frecherche%2Flocation%2Ffrance%3Fcamera%3D15_2.5733003_44.3511276_0_0",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "83.55 m²" },
      { label: "Pièces", value: "4 pièces · 3 ch." },
      { label: "Étage", value: "8e" },
      { label: "Meublé", value: "✅ Oui" },
      { label: "Parking", value: "❌ Non" },
      { label: "Extérieur", value: "Balcon" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État", value: "Entretenu" },
      { label: "DPE", value: "E · GES E" },
      { label: "Chauffage", value: "Non communiqué" },
      { label: "Exposition", value: "Plein Sud" },
      { label: "Transports", value: "Non communiqué" },
    ],
    particularites: "🏠 Cave · 🛋️ Meublé",
    note: "Appartement meublé T4 de 83,55m² à Chamalières, dernier étage d'un immeuble de huit étages avec ascenseur. Comporte 3 chambres, cuisine équipée, salle de bain moderne et balcon plein sud. Situé dans un quartier agréable, à proximité de tous les commerces et transports nécessaires. Offre vue dégagée et tranquillité appréciable. Visite possible.",
  },

  /* SUPPRIMÉ jour 3
  {
      id: 14,
      jour: 3,
      ville: "Roanne",
      titre: "Centre-ville - Varenne, Roanne (42300)",
      sous_titre: "Appartement · Location vide",
      coords: [46.033356, 4.077356],
      zoom: 16,
      tooltip: "Centre-ville - Varenne, Roanne (42300)",
      loyer: 429,
      lien: "https://www.bienici.com/annonce/location/roanne/appartement/2pieces/hektor-roannaisadb-2252?q=%2Frecherche%2Flocation%2Ffrance%3Fcamera%3D15_2.5733003_44.3511276_0_0",
      source: "Bien'ici",
      badges: [
        { label: "Surface", value: "55 m²" },
        { label: "Pièces", value: "2 pièces · 1 ch." },
        { label: "Étage", value: "" },
        { label: "Meublé", value: "❌ Non" },
        { label: "Parking", value: "❌ Non" },
        { label: "Extérieur", value: "❌ Non" },
        { label: "Année construction", value: "Non communiquée" },
        { label: "État", value: "Entretenu" },
        { label: "DPE", value: "D · GES D" },
        { label: "Chauffage", value: "radiateur gaz individuel" },
        { label: "Exposition", value: "Non communiquée" },
        { label: "Transports", value: "Non communiqué" },
      ],
      particularites: "",
      note: "Appartement de type 2bis, 55m2, rez-de-chaussée, Roanne. Cuisine ouverte, salon en enfilade, chambre, douche, wc indépendant, chauffage individuel gaz, bon état. Disponible immédiatement. DPE: D, GES: D.",
    },
  */
  {
    id: 13,
    jour: 3,
    ville: "Roanne",
    titre: "Centre-ville - Varenne, Roanne (42300)",
    sous_titre: "Appartement · Location vide",
    coords: [46.033356, 4.077356],
    zoom: 16,
    tooltip: "Centre-ville - Varenne, Roanne (42300)",
    loyer: 429,
    lien: "https://www.bienici.com/annonce/location/roanne/appartement/2pieces/hektor-roannaisadb-2252?q=%2Frecherche%2Flocation%2Ffrance%3Fcamera%3D15_2.5733003_44.3511276_0_0",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "55 m²" },
      { label: "Pièces", value: "2 pièces · 1 ch." },
      { label: "Étage", value: "Rez-de-chaussée" },
      { label: "Meublé", value: "❌ Non" },
      { label: "Parking", value: "✅ Oui" },
      { label: "Extérieur", value: "❌ Non" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État", value: "Entretenu" },
      { label: "DPE", value: "D · GES D" },
      { label: "Chauffage", value: "Radiateur gaz individuel" },
      { label: "Exposition", value: "Non communiquée" },
      { label: "Transports", value: "Non communiqué" },
    ],
    particularites: "",
    note: "Appartement de 55m² au rez-de-chaussée, avec entrée, cuisine ouverte, salle d'eau, wc indépendant, chauffage gaz, réparations nécessaires. Disponible immédiatement, situé à Roanne.",
  },

  /* SUPPRIMÉ jour 3
  {
      jour: 3,
      ville: "Vichy",
      titre: "Coeur de Ville, Vichy (03200)",
      sous_titre: "Appartement · Location vide",
      coords: [46.125516, 3.422633],
      zoom: 16,
      tooltip: "Coeur de Ville, Vichy (03200)",
      loyer: 1130,
      lien: "https://www.bienici.com/annonce/location/vichy/appartement/3pieces/ag030607-541160849?q=%2Frecherche%2Flocation%2Ffrance%3Fprix-min%3D1000%26camera%3D15_3.4122687_46.1242522_0_0",
      source: "Bien'ici",
      badges: [
        { label: "Surface", value: "82 m²" },
        { label: "Pièces", value: "3 pièces · 2 ch." },
        { label: "Étage", value: "2e" },
        { label: "Meublé", value: "❌ Non" },
        { label: "Parking", value: "❌ Non" },
        { label: "Extérieur", value: "❌ Non" },
        { label: "Année construction", value: "Non communiquée" },
        { label: "État", value: "Entretenu" },
        { label: "DPE", value: "D · GES C" },
        { label: "Chauffage", value: "collectif" },
        { label: "Exposition", value: "Non communiquée" },
        { label: "Transports", value: "Non communiqué" },
      ],
      particularites: "🏠 Cave · ☀️ Lumineux",
      note: "Vichy centre : appartement T3 lumineux de 82,5 m², ascenseur, proche commerces, transports et services. Sur 2 étages, comprend séjour lumineux, cuisine équipée, 2 chambres, salle d'eau, cellier et cave. Chauffage et eau compris dans charges. Risques immobiliers détaillés sur le site Géorisques.",
    },
  */

  /* SUPPRIMÉ jour 3
  {
      id: 13,
      jour: 3,
      ville: "Saint-Alban-Leysse",
      titre: "Saint-Alban-Leysse, Saint-Alban-Leysse (73230)",
      sous_titre: "Maison · Location meublée",
      coords: [45.583521, 5.960448],
      zoom: 16,
      tooltip: "Saint-Alban-Leysse, Saint-Alban-Leysse (73230)",
      loyer: 3800,
      lien: "https://www.bienici.com/annonce/location/saint-alban-leysse/maison/7pieces/apimo-87333363?q=%2Frecherche%2Flocation%2Ffrance%3Fprix-min%3D3000%26camera%3D7_2.9482444_46.09456_0_0",
      source: "Bien'ici",
      badges: [
        { label: "Surface", value: "179.07 m²" },
        { label: "Pièces", value: "7 pièces · 4 ch." },
        { label: "Étage", value: "" },
        { label: "Meublé", value: "✅ Oui" },
        { label: "Parking", value: "✅ Oui" },
        { label: "Extérieur", value: "Terrasse + Jardin" },
        { label: "Année construction", value: "Non communiquée" },
        { label: "État", value: "Entretenu" },
        { label: "DPE", value: "C · GES B" },
        { label: "Chauffage", value: "Au sol Pompe à chaleur Individuel" },
        { label: "Exposition", value: "Non communiquée" },
        { label: "Transports", value: "Non communiqué" },
      ],
      particularites: "🏊 Piscine · 🔇 Calme · ☀️ Lumineux · 🛋️ Meublé · ❄️ Climatisation",
      note: "Villa architecte de 2005, calme et privilégié quartier à Saint-Alban-Leysse. Édifiée sur 2000 m² plat, 4 chambres, meublée, piscine, grande couverte terrasse, terrain de boules, double garage. Proche église, proximité commerces et transports.",
    },
  */
  {
    id: 12,
    jour: 3,
    ville: "Saint-Alban-Leysse",
    titre: "Saint-Alban-Leysse, Saint-Alban-Leysse (73230)",
    sous_titre: "Maison · Location meublée",
    coords: [45.583521, 5.960448],
    zoom: 16,
    tooltip: "Saint-Alban-Leysse, Saint-Alban-Leysse (73230)",
    loyer: 3800,
    lien: "https://www.bienici.com/annonce/location/saint-alban-leysse/maison/7pieces/apimo-87333363?q=%2Frecherche%2Flocation%2Ffrance%3Fprix-min%3D3000%26camera%3D7_2.9482444_46.09456_0_0",
    source: "Bien'ici",
    badges: [
      { label: "Surface", value: "179.07 m²" },
      { label: "Pièces", value: "7 pièces · 4 ch." },
      { label: "Étage", value: "" },
      { label: "Meublé", value: "✅ Oui" },
      { label: "Parking", value: "✅ Oui" },
      { label: "Extérieur", value: "Terrasse + Jardin" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État", value: "Entretenu" },
      { label: "DPE", value: "C · GES B" },
      { label: "Chauffage", value: "Au sol Pompe à chaleur Individuel" },
      { label: "Exposition", value: "Non communiquée" },
      { label: "Transports", value: "Non communiqué" },
    ],
    particularites: "🏊 Piscine · 🔇 Calme · ☀️ Lumineux · 🛋️ Meublé · ❄️ Climatisation",
    note: "Villa d'architecte de 2005, Saint-Alban-Leysse. Calme, parcelle de 2000m². Intérieur: 4 chambres, espace de vie lumineux, salle d'eau fonctionnelle, suite parentale. Extérieur: piscine, grande terrasse couverte, terrain de boules, double garage de 42m². Proche église, proximité des commodités et accès autoroutiers. Louée meublée.",
  },


  // --- Jour 4 ---
  {
    id: 16,
    jour: 4,
    ville: "Troyes",
    titre: "Troyes (10000)",
    sous_titre: "Appartement · Location",
    coords: [48.300611, 4.081072],
    zoom: 16,
    tooltip: "Troyes (10000)",
    loyer: 500,
    lien: "https://www.seloger.com/annonce/location/grand-est/aube-10/troyes-10000/263KADHX9VHR?ln=classified_search_results_map&serp_view=map&search=distributionTypes%3DRent%26estateTypes%3DHouse%2CApartment%26locations%3DeyJwbGFjZUlkIjoiQUQwOEZSODExMyIsInJhZGl1cyI6NDYsInBvbHlsaW5lIjoiZ31fekd5e31LfHBAYnlVYHNDbHxUZm9GaGRTfmFJfnJQZmhLfGtNYF9NZnNJbmROem1FZHdOYGFBbnZOdWtBbGJOe3ZFfHtMZ3lJbmRLX25Nan5IfXBQYGxGZ35SfHBDb3NUaHBAb25VaXBAcW5VfXBDbXNUYWxGaX5Sa35Ie3BQb2RLYW5NfXtMZ3lJbWJOe3ZFb3ZOc2tBZXdOYGFBb2ROem1FYV9NZnNJZ2hLfGtNX2JJfnJQZ29GZmRTYXNDbnxUfXBAYnlVIiwiY29vcmRpbmF0ZXMiOnsibGF0Ijo0NS45NTgzMzkzNDI2NzkyOTUsImxuZyI6Mi4xMjQyOTIzNzU4NjY2MTY2fX0%26method%3Dform#ln=classified_search_results_map&m=classified_search_results_map_classified_classified_detail_M",
    source: "SeLoger",
    badges: [
      { label: "Surface", value: "47,32 m²" },
      { label: "Pièces", value: "2 pièces · 1 ch." },
      { label: "Étage", value: "1e · sans ascenseur" },
      { label: "Meublé", value: "N/A" },
      { label: "Parking", value: "Non" },
      { label: "Extérieur", value: "Non" },
      { label: "Année construction", value: "Non communiquée" },
      { label: "État", value: "Entretenu" },
      { label: "DPE", value: "Non communiqué" },
      { label: "Chauffage", value: "Chauffage central: Radiateur Sources d'é" },
      { label: "Exposition", value: "Non communiquée" },
      { label: "Transports", value: "Non communiqué" },
    ],
    particularites: "🏠 Cave",
    note: "Appartement de 2 pièces à louer dans le centre-ville de Troyes (10000). Inclut 1 chambre, cuisine équipée et cellier. Proximité de commerces et transports.",
  },

];



